//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacersModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceResults
    {
        public int Id { get; set; }
        public int RaceId { get; set; }
        public int RacerId { get; set; }
        public int TeamId { get; set; }
        public int Position { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Grid { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Laps { get; set; }
        public string Retired { get; set; }
    
        public virtual Races Races { get; set; }
        public virtual Racers Racers { get; set; }
    }
}
