//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacersModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearResultsTeam
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public int TeamId { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<decimal> Points { get; set; }
    
        public virtual Teams Teams { get; set; }
    }
}
