//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        public int DateKey { get; set; }
        public Nullable<System.DateTime> FDateTime { get; set; }
        public string FDate { get; set; }
        public int FTheYear { get; set; }
        public byte FFiscal_Period { get; set; }
        public Nullable<byte> FHalf_of_Year { get; set; }
        public string FTheHalf { get; set; }
        public string FTheQuarter { get; set; }
        public byte FQuarter_of_Year { get; set; }
        public string FTheMoth { get; set; }
        public byte FMonth_of_Year { get; set; }
        public byte FWeek_of_Year { get; set; }
        public byte FDay_of_Month { get; set; }
        public string FTheDay { get; set; }
        public string FTheDay_chs { get; set; }
        public string FTheDay_en { get; set; }
        public string FTheMonth_chs { get; set; }
        public string FTheMoth_en { get; set; }
        public string FTheQuarter_chs { get; set; }
        public string FTheQuarter_en { get; set; }
        public Nullable<byte> FDay_of_Week { get; set; }
        public string FHalfYear_chs { get; set; }
        public Nullable<int> FFiveDay_of_Month { get; set; }
        public Nullable<System.DateTime> FDateMonth { get; set; }
        public string FFiveDay_of_Month_chs { get; set; }
    }
}
