//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactOrderInfo_ODS
    {
        public int Seqno { get; set; }
        public long OrderID { get; set; }
        public Nullable<int> OrderCustomerId { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderDateKey { get; set; }
        public string OrderAddress { get; set; }
        public Nullable<int> OrderHourKey { get; set; }
        public Nullable<int> OrderAreaID { get; set; }
        public Nullable<decimal> OrderWeight { get; set; }
    }
}
