//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactOrderProduct_ODS
    {
        public int SeqNo { get; set; }
        public long OrdPrdOrderID { get; set; }
        public int OrdPrdProductId { get; set; }
        public Nullable<int> OrdPrdCustomerID { get; set; }
        public Nullable<int> OrdPrdHour { get; set; }
        public Nullable<int> OrdPrdDateKey { get; set; }
        public Nullable<int> OrdPrdAreaID { get; set; }
        public Nullable<double> OrdPrdProductPrice { get; set; }
        public Nullable<double> OrdPrdProductNum { get; set; }
        public Nullable<double> OrdPrdAmount { get; set; }
        public Nullable<decimal> OrdPrdWeight { get; set; }
    }
}
