//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BIDWDemoEntities : DbContext
    {
        public BIDWDemoEntities()
            : base("name=BIDWDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimArea> DimArea { get; set; }
        public virtual DbSet<DimDate> DimDate { get; set; }
        public virtual DbSet<DimHour> DimHour { get; set; }
        public virtual DbSet<DimProduct> DimProduct { get; set; }
        public virtual DbSet<FactCustomerInfo> FactCustomerInfo { get; set; }
        public virtual DbSet<FactOrderInfo> FactOrderInfo { get; set; }
        public virtual DbSet<FactOrderInfo_ODS> FactOrderInfo_ODS { get; set; }
        public virtual DbSet<FactOrderProduct> FactOrderProduct { get; set; }
        public virtual DbSet<FactOrderProduct_ODS> FactOrderProduct_ODS { get; set; }
    
        [DbFunction("BIDWDemoEntities", "UF_SSRS_SPLIT_PARAM")]
        public virtual IQueryable<UF_SSRS_SPLIT_PARAM_Result> UF_SSRS_SPLIT_PARAM(string pString, string pDelimiter)
        {
            var pStringParameter = pString != null ?
                new ObjectParameter("pString", pString) :
                new ObjectParameter("pString", typeof(string));
    
            var pDelimiterParameter = pDelimiter != null ?
                new ObjectParameter("pDelimiter", pDelimiter) :
                new ObjectParameter("pDelimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<UF_SSRS_SPLIT_PARAM_Result>("[BIDWDemoEntities].[UF_SSRS_SPLIT_PARAM](@pString, @pDelimiter)", pStringParameter, pDelimiterParameter);
        }
    
        public virtual int ETL_FromBIWebsite()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ETL_FromBIWebsite");
        }
    
        public virtual int IncrementETL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IncrementETL");
        }
    
        public virtual int RPT_Customer_Price(Nullable<System.DateTime> dateBeg, Nullable<System.DateTime> dateend, string city, string province)
        {
            var dateBegParameter = dateBeg.HasValue ?
                new ObjectParameter("dateBeg", dateBeg) :
                new ObjectParameter("dateBeg", typeof(System.DateTime));
    
            var dateendParameter = dateend.HasValue ?
                new ObjectParameter("dateend", dateend) :
                new ObjectParameter("dateend", typeof(System.DateTime));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var provinceParameter = province != null ?
                new ObjectParameter("Province", province) :
                new ObjectParameter("Province", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RPT_Customer_Price", dateBegParameter, dateendParameter, cityParameter, provinceParameter);
        }
    
        public virtual int RPT_Customer_Price_A(Nullable<System.DateTime> dateBeg, Nullable<System.DateTime> dateend, string city, string province)
        {
            var dateBegParameter = dateBeg.HasValue ?
                new ObjectParameter("dateBeg", dateBeg) :
                new ObjectParameter("dateBeg", typeof(System.DateTime));
    
            var dateendParameter = dateend.HasValue ?
                new ObjectParameter("dateend", dateend) :
                new ObjectParameter("dateend", typeof(System.DateTime));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var provinceParameter = province != null ?
                new ObjectParameter("Province", province) :
                new ObjectParameter("Province", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RPT_Customer_Price_A", dateBegParameter, dateendParameter, cityParameter, provinceParameter);
        }
    
        public virtual int RPT_Customer_Type(Nullable<System.DateTime> dateBeg, Nullable<System.DateTime> dateend, string city, string province)
        {
            var dateBegParameter = dateBeg.HasValue ?
                new ObjectParameter("dateBeg", dateBeg) :
                new ObjectParameter("dateBeg", typeof(System.DateTime));
    
            var dateendParameter = dateend.HasValue ?
                new ObjectParameter("dateend", dateend) :
                new ObjectParameter("dateend", typeof(System.DateTime));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var provinceParameter = province != null ?
                new ObjectParameter("Province", province) :
                new ObjectParameter("Province", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RPT_Customer_Type", dateBegParameter, dateendParameter, cityParameter, provinceParameter);
        }
    
        public virtual ObjectResult<UP_Report_AreaInfo_Show_Result> UP_Report_AreaInfo_Show()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UP_Report_AreaInfo_Show_Result>("UP_Report_AreaInfo_Show");
        }
    }
}
