//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class test1
    {
        public int Id { get; set; }
        public string CustomerNameT { get; set; }
        public string CustomerAreaName { get; set; }
    
        public virtual DimArea AreaName { get; set; }
        public virtual FactCustomerInfo CustomerName { get; set; }
    }
}
